### ISSUE TITLE
Fedcred fails on adfs authentication

### ISSUE THREAD

**Issue by zachzeid** [broamski/aws-fedcred#2]
```Traceback (most recent call last):
  File "/usr/local/bin/fedcred", line 16, in <module>
    main()
  File "/usr/local/bin/fedcred", line 13, in main
    Adfs(config).auth()
  File "/Library/Python/2.7/site-packages/fedcred/providers/adfs.py", line 51, in auth
    response = session.post(action, data=payload_dict,
UnboundLocalError: local variable 'action' referenced before assignment```

It appears that action is empty because there is a landing page before being able to assume the adfs role into aws.  However, the ability to paste the adfs url `https://<adfs url>/?loginToRp=urn:amazon:webservices` into the browser and passing the credentials when prompted works.

**Comment by zachzeid** [comment]
issue solved with https://github.com/broamski/aws-fedcred/pull/4
