### ISSUE TITLE
Add support for python3.x

### ISSUE THREAD

**Issue by zachzeid** [broamski/aws-fedcred#7]
```
Traceback (most recent call last):
  File "/home/zzeid/fedcred/bin/fedcred", line 16, in <module>
    main()
  File "/home/zzeid/fedcred/bin/fedcred", line 13, in main
    Adfs(config).auth()
```

Workaround is to use a virtualenv.

**Comment by joearnet** [comment]
fwiw i'm running manjaro x64, with python 2.7.4 in a virtualenv 2 env. I'm getting this:

(fedcred)  jarnet@jarnet-homejaro  ~/Code/Cengage/fedcred  fedcred
Enter you username: jarnet
Enter your password: 
Traceback (most recent call last):
  File "/home/jarnet/Code/Cengage/fedcred/bin/fedcred", line 16, in <module>
    main()
  File "/home/jarnet/Code/Cengage/fedcred/bin/fedcred", line 13, in main
    Adfs(config).auth()
  File "/home/jarnet/Code/Cengage/fedcred/lib/python2.7/site-packages/fedcred/providers/adfs.py", line 68, in auth
    arn_to_assume = common.get_arns_from_assertion(assertion)
  File "/home/jarnet/Code/Cengage/fedcred/lib/python2.7/site-packages/fedcred/common.py", line 80, in get_arns_from_assertion
    root = ET.fromstring(base64.b64decode(assertion))
  File "/usr/lib64/python2.7/base64.py", line 75, in b64decode
    return binascii.a2b_base64(s)
TypeError: a2b_base64() argument 1 must be string or buffer, not None

**Comment by joearnet** [comment]
disregard above issue, username was not submitted correctly:
was doing: jarnet (but needed to be ADDOMAIN\jarnet
derp derp

**Comment by broamski** [comment]
Hey! Are these two issues related?

**Comment by broamski** [comment]
Or can I close this?

**Comment by zachzeid** [comment]
This can be closed.  Sorry!
